# Generated by Django 2.2.13 on 2020-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='allottedBy',
            field=models.CharField(blank=True, choices=[('0', 'DSA'), ('1', 'Self')], default='0', max_length=2, verbose_name='Allotted By'),
        ),
    ]
