# Generated by Django 2.2.13 on 2020-09-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistReport', '0002_response_allottedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='modifiedOn',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Modified on'),
        ),
    ]
