# Generated by Django 2.2.13 on 2020-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistReport', '0003_auto_20200925_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=2, verbose_name='Month')),
                ('year', models.CharField(blank=True, max_length=4, verbose_name='Year')),
                ('edit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Edit permission')),
                ('view', models.BooleanField(blank=True, default=True, null=True, verbose_name='View permission')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
            },
        ),
    ]
