# Generated by Django 2.2.13 on 2020-09-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistReport', '0004_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distreport',
            name='reportingMonth',
        ),
        migrations.RemoveField(
            model_name='distreport',
            name='reportingYear',
        ),
        migrations.AddField(
            model_name='distreport',
            name='month',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DistReport.Month'),
        ),
    ]
