# Generated by Django 2.2.13 on 2020-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistReport', '0005_auto_20200926_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskText',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Task'),
        ),
    ]
