# Generated by Django 2.2.13 on 2021-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventNo', models.CharField(default='99', max_length=2, verbose_name='Serial Number')),
                ('eventName', models.CharField(max_length=50, verbose_name='Name')),
                ('eventDescription', models.TextField(verbose_name='Event Description')),
                ('eventCategory', models.CharField(choices=[('1', 'Professional Development'), ('2', 'Community Service'), ('3', 'International Service')], default='0', max_length=2, verbose_name='Avenue')),
                ('eventInstagramPost', models.TextField(verbose_name='Instagram Post')),
                ('eventVisibility', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'WhatWeDo',
                'verbose_name_plural': 'WhatWeDos',
            },
        ),
    ]
