# Generated by Django 2.2.13 on 2021-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial_whatWeDo'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='FAQ',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('question', models.CharField(blank=True, max_length=100, verbose_name='Question')),
        #         ('answer', models.CharField(blank=True, max_length=1000, verbose_name='Answer')),
        #     ],
        #     options={
        #         'verbose_name': 'FAQ',
        #         'verbose_name_plural': 'FAQs',
        #     },
        # ),
        migrations.AlterField(
            model_name='whatwedo',
            name='eventCategory',
            field=models.CharField(choices=[('1', 'Professional Development'), ('2', 'Club Service'), ('3', 'International Service'), ('4', 'Community Service'), ('5', 'Foundation'), ('6', 'Financial Service'), ('7', 'Public Image')], default='0', max_length=2, verbose_name='Avenue'),
        ),
    ]
