# Generated by Django 2.2.13 on 2020-09-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='distId',
        ),
        migrations.AlterField(
            model_name='club',
            name='rotaryId',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Rotary Id'),
        ),
    ]
