# Generated by Django 2.2.13 on 2020-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20200909_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtrole',
            name='distRoleName',
            field=models.CharField(max_length=60, verbose_name='District Role Name'),
        ),
    ]
