# Generated by Django 2.2.13 on 2020-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20200912_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtrole',
            name='distRoleId',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
