# Generated by Django 2.2.13 on 2020-09-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20200918_0218'),
        ('Auth', '0003_remove_account_date_joined'),
    ]

    operations = [
    ]
