# Generated by Django 2.2.13 on 2020-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_merge_20200925_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtrole',
            name='distRoleSName',
            field=models.CharField(default='', max_length=60, verbose_name='District Role Short'),
        ),
    ]
