# Generated by Django 2.2.13 on 2020-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20200930_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtrole',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='Under DS-A?'),
        ),
    ]
