# Generated by Django 2.2.13 on 2020-10-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0004_auto_20200909_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='suggestions',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Suggestions'),
        ),
    ]
