# Generated by Django 2.2.13 on 2020-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0005_auto_20201002_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timepass',
            fields=[
                ('bulletinId', models.CharField(blank=True, max_length=32, primary_key=True, serialize=False, verbose_name='Bulletin Id')),
            ],
        ),
    ]
