# Generated by Django 2.2.13 on 2020-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0006_timepass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timepass',
            name='bulletinId',
            field=models.CharField(blank=True, max_length=24, primary_key=True, serialize=False, verbose_name='Bulletin Id'),
        ),
    ]
